### ISSUE TITLE
excellent code practices followed in HTML

### ISSUE THREAD

**Issue by ad3429** [thecuriousteach/f1-3-c2p1-colmar-academy#1]
https://github.com/thecuriousteach/f1-3-c2p1-colmar-academy/blob/master/colmar/index.html#L10-L223

Your HTML is very clear/easy to follow and you generally followed excellent code practices such as commenting, indenting, etc. It is clear that you are growing as a developer -- great job!

**Comment by thecuriousteach** [comment]
Thank you
